name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false #has to be false if we want all the tests to run
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: #check versions from time to time
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    name: Test
    runs-on: ${{matrix.os}} 

    steps:
      - name: checkout code
        uses: actions/checkout@v4 #check version from time to time
      
      - name: set up Python 
        uses: actions/setup-python@v5 #check version from time to time
        with:
          python-version: ${{matrix.python-version}} 

      - name: install dependencies
        run: python -m pip install pytest . 

      - name: run tests
        run: pytest 


