name: CI

on:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false #has to be false if we want all the tests to run
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: #check versions from time to time
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    name: Test
    runs-on: ${{matrix.os}} 

    steps:
      - name: checkout code
        uses: actions/checkout@v4 #check version from time to time
      
      - name: set up Python 
        uses: actions/setup-python@v5 #check version from time to time
        with:
          python-version: ${{matrix.python-version}} 

      #install all dependencies
      - name: install numpy
        run: python -m pip install numpy

      - name: install matplotlib
        run: python -m pip install matplotlib

      - name: install tqdm
        run: python -m pip install tqdm

      - name: install tueplots
        run: python -m pip install tueplots

      - name: install scipy
        run: python -m pip install scipy

      - name: install flet
        run: python -m pip install flet

      - name: install logging
        run: python -m pip install logging

      #- name: install time
     #   run: python -m pip install time



      # install pytest
      - name: install pytest
        run: python -m pip install pytest 

      #run the tests
      - name: run tests
        run: pytest 


